{"name":"testApiForNonExistingUser","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Wrong Error Response Details!\n\tWrong expected message expected [User nonexistinguser230203163633 doesn't exists!] but found [User 'nonexistinguser230203163633' doesn't exist!]","trace":"java.lang.AssertionError: Wrong Error Response Details!\n\tWrong expected message expected [User nonexistinguser230203163633 doesn't exists!] but found [User 'nonexistinguser230203163633' doesn't exist!]\r\n\tat org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)\r\n\tat tests.api.VerifyErrorGetNonExistingUser.testApiForNonExistingUser(VerifyErrorGetNonExistingUser.java:60)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)\r\n\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)\r\n\tat org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)\r\n\tat org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:794)\r\n\tat org.testng.TestRunner.run(TestRunner.java:596)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:377)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:276)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1134)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1063)\r\n\tat org.testng.TestNG.run(TestNG.java:1031)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)\r\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1675438594222,"stop":1675438598675,"uuid":"1b077866-db15-48eb-b980-7130d3f571c9","historyId":"e0730f67354070a4289e018e05092c91","fullName":"tests.api.VerifyErrorGetNonExistingUser.testApiForNonExistingUser","labels":[{"name":"package","value":"tests.api.VerifyErrorGetNonExistingUser"},{"name":"testClass","value":"tests.api.VerifyErrorGetNonExistingUser"},{"name":"testMethod","value":"testApiForNonExistingUser"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"GenericTAFramework"},{"name":"subSuite","value":"tests.api.VerifyErrorGetNonExistingUser"},{"name":"host","value":"EN310366"},{"name":"thread","value":"10880@EN310366.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"story","value":"API Testing"},{"name":"severity","value":"critical"}],"links":[]}