{"name":"testVerifyErrorGetUserNoPermission","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Wrong Error Response Details!\n\tWrong timestamp expected [true] but found [false]","trace":"java.lang.AssertionError: Wrong Error Response Details!\n\tWrong timestamp expected [true] but found [false]\r\n\tat org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)\r\n\tat tests.api.VerifyErrorGetUserNoPermission.testVerifyErrorGetUserNoPermission(VerifyErrorGetUserNoPermission.java:67)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)\r\n\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)\r\n\tat org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)\r\n\tat org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:794)\r\n\tat org.testng.TestRunner.run(TestRunner.java:596)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:377)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:276)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1134)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1063)\r\n\tat org.testng.TestNG.run(TestNG.java:1031)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)\r\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1675439518969,"stop":1675439519514,"uuid":"c8d4ba4d-23be-416e-98c0-a0c7a9db1997","historyId":"8ea7ddebc547f4bb8dd47f2b5bfcfc8e","fullName":"tests.api.VerifyErrorGetUserNoPermission.testVerifyErrorGetUserNoPermission","labels":[{"name":"package","value":"tests.api.VerifyErrorGetUserNoPermission"},{"name":"testClass","value":"tests.api.VerifyErrorGetUserNoPermission"},{"name":"testMethod","value":"testVerifyErrorGetUserNoPermission"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"GenericTAFramework"},{"name":"subSuite","value":"tests.api.VerifyErrorGetUserNoPermission"},{"name":"host","value":"EN310366"},{"name":"thread","value":"20232@EN310366.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"story","value":"Access API without proper permission"},{"name":"severity","value":"critical"}],"links":[]}